// Auto-generated by NBA sim — do not edit manually
// Last updated: 2026-03-13T22:30:00

const HISTORY_DATA = {
  "simulation_start": "2026-03-08",
  "initial_bankroll": 1000.0,
  "sport": "NBA",
  "games": [
    {
      "session": 1,
      "start_date": "2026-03-08",
      "end_date": null,
      "peak_bankroll": 2342.25,
      "final_bankroll": null,
      "net_pnl": null,
      "total_bets": 13,
      "wins": 9,
      "losses": 2
    }
  ],
  "entries": [
    {
      "entry_id": "nba_entry_20260308",
      "session": 1,
      "timestamp": "2026-03-08T19:00:00",
      "type": "bets_placed",
      "bankroll_before": 1000.0,
      "total_staked": 400.0,
      "bankroll_after": 1439.0,
      "bets": [
        {
          "id": "nba_bet_20260308_001",
          "match": "Miami Heat vs Detroit Pistons",
          "time": "22:00",
          "pick": "Miami Heat ML",
          "odds": 1.98,
          "stake": 150.0,
          "potential_return": 297.0,
          "confidence": 65,
          "anchor_players": [],
          "result": "WON",
          "returned": 297.0,
          "pnl": 147.0,
          "settled_at": "2026-03-09T14:00:00"
        },
        {
          "id": "nba_bet_20260308_002",
          "match": "Sacramento Kings vs Chicago Bulls",
          "time": "01:00",
          "pick": "Sacramento Kings ML",
          "odds": 2.0,
          "stake": 150.0,
          "potential_return": 300.0,
          "confidence": 70,
          "anchor_players": ["De'Aaron Fox", "Domantas Sabonis"],
          "result": "WON",
          "returned": 300.0,
          "pnl": 150.0,
          "settled_at": "2026-03-09T14:00:00"
        },
        {
          "id": "nba_bet_20260308_003",
          "match": "Phoenix Suns vs Charlotte Hornets",
          "time": "02:00",
          "pick": "Phoenix Suns ML",
          "odds": 2.42,
          "stake": 100.0,
          "potential_return": 242.0,
          "confidence": 52,
          "anchor_players": [],
          "result": "WON",
          "returned": 242.0,
          "pnl": 142.0,
          "settled_at": "2026-03-09T14:00:00"
        }
      ],
      "summary": "Opening bets — 3 picks totalling €400. ALL 3 WON! Heat 121-110 Pistons, Kings 126-110 Bulls, Suns 111-99 Hornets. Net P&L: +€439. Bankroll: €1000 → €1439."
    },
    {
      "entry_id": "nba_entry_20260309",
      "session": 1,
      "timestamp": "2026-03-09T22:30:00",
      "type": "bets_placed",
      "bankroll_before": 1439.0,
      "total_staked": 790.0,
      "bankroll_after": 1747.25,
      "bets": [
        {
          "id": "nba_bet_20260309_001",
          "match": "Cleveland Cavaliers vs Philadelphia 76ers",
          "time": "00:00",
          "pick": "Cleveland Cavaliers -12.5",
          "odds": 1.91,
          "stake": 360.0,
          "potential_return": 687.6,
          "confidence": 80,
          "anchor_players": ["Donovan Mitchell"],
          "result": "WON",
          "returned": 687.6,
          "pnl": 327.6,
          "settled_at": "2026-03-10T14:00:00"
        },
        {
          "id": "nba_bet_20260309_002",
          "match": "Oklahoma City Thunder vs Denver Nuggets",
          "time": "00:30",
          "pick": "Denver Nuggets +7.5",
          "odds": 1.91,
          "stake": 215.0,
          "potential_return": 410.65,
          "confidence": 65,
          "anchor_players": ["Nikola Jokic", "Jamal Murray"],
          "result": "WON",
          "returned": 410.65,
          "pnl": 195.65,
          "settled_at": "2026-03-10T14:00:00"
        },
        {
          "id": "nba_bet_20260309_003",
          "match": "Brooklyn Nets vs Memphis Grizzlies",
          "time": "23:30",
          "pick": "Memphis Grizzlies ML",
          "odds": 1.75,
          "stake": 215.0,
          "potential_return": 376.25,
          "confidence": 64,
          "anchor_players": [],
          "result": "LOST",
          "returned": 0,
          "pnl": -215.0,
          "settled_at": "2026-03-10T14:00:00"
        }
      ],
      "summary": "Day 2 settle — CLE ✅ covered -12.5 (115-101, margin +14), DEN ✅ covered +7.5 (OKC 129-126, lost by only 3), MEM ❌ ML LOST (BKN 126-115, Nets bench explosion). Day 2 net P&L: +€308.25. Total P&L: +€747.25. Bankroll: €649 → €1,747.25."
    },
    {
      "entry_id": "nba_entry_20260310",
      "session": 1,
      "timestamp": "2026-03-10T22:30:00",
      "type": "bets_placed",
      "bankroll_before": 1747.25,
      "total_staked": 665.0,
      "bankroll_after": 1082.25,
      "bets": [
        {
          "id": "nba_bet_20260310_001",
          "match": "San Antonio Spurs vs Boston Celtics",
          "time": "00:00",
          "pick": "San Antonio Spurs -3.5",
          "odds": 1.8,
          "stake": 315.0,
          "potential_return": 567.0,
          "confidence": 68,
          "anchor_players": ["Victor Wembanyama"],
          "result": "WON",
          "returned": 567.0,
          "pnl": 252.0,
          "settled_at": "2026-03-11T14:00:00"
        },
        {
          "id": "nba_bet_20260310_002",
          "match": "Los Angeles Lakers vs Minnesota Timberwolves",
          "time": "03:00",
          "pick": "Los Angeles Lakers ML",
          "odds": 2.05,
          "stake": 175.0,
          "potential_return": 358.75,
          "confidence": 47,
          "anchor_players": ["Luka Doncic"],
          "result": "WON",
          "returned": 358.75,
          "pnl": 183.75,
          "settled_at": "2026-03-11T14:00:00"
        },
        {
          "id": "nba_bet_20260310_003",
          "match": "Chicago Bulls vs Golden State Warriors",
          "time": "03:00",
          "pick": "Chicago Bulls +6.5",
          "odds": 1.91,
          "stake": 175.0,
          "potential_return": 334.25,
          "confidence": 55,
          "anchor_players": [],
          "result": "WON",
          "returned": 334.25,
          "pnl": 159.25,
          "settled_at": "2026-03-11T14:00:00"
        }
      ],
      "summary": "Day 3 settle (11 Mar) — SAS ✅ -3.5 WON (125-116, Wemby 39 pts/11 reb/8 3PT, margin +9), LAL ✅ ML WON (120-106, Luka 31/11/11 triple-double, Reaves 31 pts), CHI ✅ +6.5 WON (Bulls 130-124 OT, Buzelis career-high 41 pts). Day 3 net P&L: +€595.00. Total P&L: +€1,342.25. New peak: €2,342.25."
    },
    {
      "entry_id": "nba_entry_20260312",
      "session": 1,
      "timestamp": "2026-03-12T23:00:00",
      "type": "bets_placed",
      "bankroll_before": 2342.25,
      "total_staked": 725.0,
      "bankroll_after": 1617.25,
      "cancelled_picks": [
        {
          "id": "nba_draft_20260311_001_cancelled",
          "match": "New Orleans Pelicans vs Toronto Raptors",
          "pick": "New Orleans Pelicans ML",
          "odds_drafted": 1.98,
          "odds_at_commit": 2.15,
          "reason": "Significant line movement (>0.22 against pick). Pelicans 21-45 (tanking), Raptors 36-28 (playoff, 19-11 road). Flipped to Raptors ML."
        }
      ],
      "bets": [
        {
          "id": "nba_bet_20260312_001",
          "match": "Los Angeles Clippers vs Minnesota Timberwolves",
          "time": "02:30",
          "pick": "Los Angeles Clippers ML",
          "odds": 1.74,
          "stake": 350.0,
          "potential_return": 609.0,
          "confidence": 58,
          "anchor_players": [],
          "result": "WON",
          "returned": 609.0,
          "pnl": 259.0,
          "settled_at": "2026-03-13T14:00:00"
        },
        {
          "id": "nba_bet_20260312_002",
          "match": "New Orleans Pelicans vs Toronto Raptors",
          "time": "00:00",
          "pick": "Toronto Raptors ML",
          "odds": 1.76,
          "stake": 375.0,
          "potential_return": 660.0,
          "confidence": 62,
          "anchor_players": [],
          "result": "LOST",
          "returned": 0,
          "pnl": -375.0,
          "settled_at": "2026-03-13T14:00:00"
        }
      ],
      "summary": "Day 5 settle (13 Mar) — LAC ✅ ML WON (Clippers 153-128, Kawhi 45pts), TOR ❌ ML LOST (NOP 122-111). Day net P&L: −€116. Cumulative P&L: +€1,226.25. Bankroll: €2,342.25 → €2,226.25."
    },
    {
      "entry_id": "nba_entry_20260313",
      "session": 1,
      "timestamp": "2026-03-13T22:30:00",
      "type": "bets_placed",
      "bankroll_before": 2226.25,
      "total_staked": 780.0,
      "bankroll_after": 1446.25,
      "cancelled_picks": [
        {
          "id": "nba_draft_20260312_001",
          "match": "Detroit Pistons vs Philadelphia 76ers",
          "pick": "Detroit Pistons -14.5",
          "odds_drafted": 1.80,
          "odds_at_commit": 1.75,
          "reason": "Game AO VIVO (in progress) at commit time — pre-game betting window closed. Spread widened to -17.5 (Adem Bona OUT added, Andre Drummond QUESTIONABLE for PHI)."
        }
      ],
      "bets": [
        {
          "id": "nba_bet_20260313_001",
          "match": "San Antonio Spurs vs Denver Nuggets",
          "time": "01:00",
          "pick": "Denver Nuggets ML",
          "odds": 2.50,
          "stake": 445.0,
          "potential_return": 1112.50,
          "confidence": 65,
          "anchor_players": ["Nikola Jokic", "Jamal Murray"],
          "result": null,
          "returned": null,
          "pnl": null,
          "settled_at": null
        },
        {
          "id": "nba_bet_20260313_002",
          "match": "Oklahoma City Thunder vs Boston Celtics",
          "time": "01:30",
          "pick": "Oklahoma City Thunder -7.5",
          "odds": 1.78,
          "stake": 335.0,
          "potential_return": 596.30,
          "confidence": 62,
          "anchor_players": ["Chet Holmgren"],
          "result": null,
          "returned": null,
          "pnl": null,
          "settled_at": null
        }
      ],
      "summary": "Day 6 commit (13 Mar) — Draft pick DET -14.5 CANCELLED (game live at commit time, spread widened to -17.5). 2 late-scout picks totalling €780: DEN ML @ 2.50 (Wemby QUESTIONABLE/50-50, Jokic healthy) + OKC -7.5 @ 1.78 (Tatum OUT, Vucevic OUT for Boston). Bankroll: €2,226.25 → €1,446.25. Results at 14:00 tomorrow."
    }
  ]
};

const DRAFT_PICKS = [];
