// Auto-generated by NBA sim — do not edit manually
// Last updated: 2026-03-11T14:00:00

const HISTORY_DATA = {
  "simulation_start": "2026-03-08",
  "initial_bankroll": 1000.00,
  "sport": "NBA",
  "games": [
    {
      "session": 1,
      "start_date": "2026-03-08",
      "end_date": null,
      "peak_bankroll": 2342.25,
      "final_bankroll": null,
      "net_pnl": null,
      "total_bets": 9,
      "wins": 8,
      "losses": 1
    }
  ],
  "entries": [
    {
      "entry_id": "nba_entry_20260308",
      "session": 1,
      "timestamp": "2026-03-08T19:00:00",
      "type": "bets_placed",
      "bankroll_before": 1000.00,
      "total_staked": 400.00,
      "bankroll_after": 1439.00,
      "bets": [
        {
          "id": "nba_bet_20260308_001",
          "match": "Miami Heat vs Detroit Pistons",
          "time": "22:00",
          "pick": "Miami Heat ML",
          "odds": 1.98,
          "stake": 150.00,
          "potential_return": 297.00,
          "reasoning": "Heat near even money at 1.98 vs Pistons — historically resilient franchise under Spoelstra; competitive matchup for both teams fighting for playoff position",
          "confidence": 65,
          "anchor_players": [],
          "result": "WON",
          "returned": 297.00,
          "pnl": 147.00,
          "settled_at": "2026-03-09T14:00:00"
        },
        {
          "id": "nba_bet_20260308_002",
          "match": "Sacramento Kings vs Chicago Bulls",
          "time": "01:00",
          "pick": "Sacramento Kings ML",
          "odds": 2.00,
          "stake": 150.00,
          "potential_return": 300.00,
          "reasoning": "Kings at even money (2.00) offers excellent value; De'Aaron Fox and Domantas Sabonis-led offense capable of winning at home; road Bulls at 1.70 seems overpriced",
          "confidence": 70,
          "anchor_players": ["De'Aaron Fox", "Domantas Sabonis"],
          "result": "WON",
          "returned": 300.00,
          "pnl": 150.00,
          "settled_at": "2026-03-09T14:00:00"
        },
        {
          "id": "nba_bet_20260308_003",
          "match": "Phoenix Suns vs Charlotte Hornets",
          "time": "02:00",
          "pick": "Phoenix Suns ML",
          "odds": 2.42,
          "stake": 100.00,
          "potential_return": 242.00,
          "reasoning": "Suns at 2.42 looks undervalued for a talent-rich roster; speculative play on market overreaction to recent Suns struggles; home court advantage",
          "confidence": 52,
          "anchor_players": [],
          "result": "WON",
          "returned": 242.00,
          "pnl": 142.00,
          "settled_at": "2026-03-09T14:00:00"
        }
      ],
      "summary": "Opening bets — 3 picks totalling €400. ALL 3 WON! Heat 121-110 Pistons, Kings 126-110 Bulls, Suns 111-99 Hornets. Net P&L: +€439. Bankroll: €1000 → €1439."
    },
    {
      "entry_id": "nba_entry_20260309",
      "session": 1,
      "timestamp": "2026-03-09T22:30:00",
      "type": "bets_placed",
      "bankroll_before": 1439.00,
      "total_staked": 790.00,
      "bankroll_after": 1747.25,
      "bets": [
        {
          "id": "nba_bet_20260309_001",
          "match": "Cleveland Cavaliers vs Philadelphia 76ers",
          "time": "00:00",
          "pick": "Cleveland Cavaliers -12.5",
          "odds": 1.91,
          "stake": 360.00,
          "potential_return": 687.60,
          "reasoning": "76ers are catastrophically undermanned: Embiid OUT (oblique), Paul George OUT (suspension), Maxey OUT (finger). Cavaliers near full strength. Home court advantage.",
          "confidence": 80,
          "anchor_players": ["Donovan Mitchell"],
          "result": "WON",
          "returned": 687.60,
          "pnl": 327.60,
          "settled_at": "2026-03-10T14:00:00"
        },
        {
          "id": "nba_bet_20260309_002",
          "match": "Oklahoma City Thunder vs Denver Nuggets",
          "time": "00:30",
          "pick": "Denver Nuggets +7.5",
          "odds": 1.91,
          "stake": 215.00,
          "potential_return": 410.65,
          "reasoning": "OKC severely depleted (Jalen Williams, Hartenstein OUT). Jokic confirmed playing. Great spread value.",
          "confidence": 65,
          "anchor_players": ["Nikola Jokic", "Jamal Murray"],
          "result": "WON",
          "returned": 410.65,
          "pnl": 195.65,
          "settled_at": "2026-03-10T14:00:00"
        },
        {
          "id": "nba_bet_20260309_003",
          "match": "Brooklyn Nets vs Memphis Grizzlies",
          "time": "23:30",
          "pick": "Memphis Grizzlies ML",
          "odds": 1.75,
          "stake": 215.00,
          "potential_return": 376.25,
          "reasoning": "Michael Porter Jr. OUT for Nets. Grizzlies superior roster. Nets tanking risk.",
          "confidence": 64,
          "anchor_players": [],
          "result": "LOST",
          "returned": 0,
          "pnl": -215.00,
          "settled_at": "2026-03-10T14:00:00"
        }
      ],
      "summary": "Day 2 settle — CLE ✅ -12.5 WON, DEN ✅ +7.5 WON, MEM ❌ ML LOST (BKN 126-115). Day 2 P&L: +€308.25. Bankroll: €649 → €1,747.25."
    },
    {
      "entry_id": "nba_entry_20260310",
      "session": 1,
      "timestamp": "2026-03-10T22:30:00",
      "type": "bets_placed",
      "bankroll_before": 1747.25,
      "total_staked": 665.00,
      "bankroll_after": 1082.25,
      "bets": [
        {
          "id": "nba_bet_20260310_001",
          "match": "San Antonio Spurs vs Boston Celtics",
          "time": "00:00",
          "pick": "San Antonio Spurs -3.5",
          "odds": 1.80,
          "stake": 315.00,
          "potential_return": 567.00,
          "reasoning": "Spurs 47-17, won 15 of last 16. Celtics missing Vucevic, Tatum on 27-min restriction. Wemby dominant at home.",
          "confidence": 68,
          "anchor_players": ["Victor Wembanyama"],
          "result": "WON",
          "returned": 567.00,
          "pnl": 252.00,
          "settled_at": "2026-03-11T14:00:00"
        },
        {
          "id": "nba_bet_20260310_002",
          "match": "Los Angeles Lakers vs Minnesota Timberwolves",
          "time": "03:00",
          "pick": "Los Angeles Lakers ML",
          "odds": 2.05,
          "stake": 175.00,
          "potential_return": 358.75,
          "reasoning": "LeBron OUT 3rd straight game. Luka Doncic at home on primetime NBC. Good value at 2.05.",
          "confidence": 47,
          "anchor_players": ["Luka Doncic"],
          "result": "WON",
          "returned": 358.75,
          "pnl": 183.75,
          "settled_at": "2026-03-11T14:00:00"
        },
        {
          "id": "nba_bet_20260310_003",
          "match": "Chicago Bulls vs Golden State Warriors",
          "time": "03:00",
          "pick": "Chicago Bulls +6.5",
          "odds": 1.91,
          "stake": 175.00,
          "potential_return": 334.25,
          "reasoning": "Warriors on B2B after Utah. Draymond QUESTIONABLE. Rested Bulls acclimated to West Coast.",
          "confidence": 55,
          "anchor_players": [],
          "result": "WON",
          "returned": 334.25,
          "pnl": 159.25,
          "settled_at": "2026-03-11T14:00:00"
        }
      ],
      "summary": "Day 3 settle (11 Mar) — SAS ✅ -3.5 WON (125-116, Wemby 39/11/8 3PT), LAL ✅ ML WON (120-106, Luka 31/11/11), CHI ✅ +6.5 WON (130-124 OT, Buzelis 41). ALL 3 WON! Day 3 P&L: +€595.00. Total P&L: +€1,342.25. New peak: €2,342.25."
    }
  ]
};

const DRAFT_PICKS = [
  {
    "id": "nba_draft_20260311_001",
    "match": "New Orleans Pelicans vs Toronto Raptors",
    "time": "00:00",
    "pick": "New Orleans Pelicans ML",
    "odds": 1.98,
    "stake": 375.00,
    "potential_return": 742.50,
    "confidence": 62,
    "reasoning": [
      "Zion Williamson confirmed active — scored 24 pts in 33 min vs Lakers on March 10",
      "Pelicans at home (Smoothie King Center) — strong home-court advantage",
      "Raptors without Collin Murray-Boyles (OUT, thumb); Poeltl questionable",
      "Pelicans starting lineup intact: D. Murray, T. Murphy, H. Jones, S. Bey, Zion",
      "Herb Jones questionable (adductor) — manageable if he sits; depth is adequate",
      "Good value at 1.98 for the home team with a healthy Zion"
    ],
    "anchor_players": ["Zion Williamson"],
    "drafted_at": "2026-03-11T14:00:00"
  },
  {
    "id": "nba_draft_20260311_002",
    "match": "Los Angeles Clippers vs Minnesota Timberwolves",
    "time": "02:30",
    "pick": "Los Angeles Clippers ML",
    "odds": 1.70,
    "stake": 350.00,
    "potential_return": 595.00,
    "confidence": 58,
    "reasoning": [
      "Timberwolves on second night of back-to-back — lost to Lakers 106-120 on March 10",
      "Anthony Edwards shot only 2-for-15 (14 pts) vs Lakers — heavy fatigue carry-over risk",
      "Clippers at home (Intuit Dome) — three-game home winning streak",
      "Clippers roster bolstered by Darius Garland (acquired via Cavs trade)",
      "Road back-to-back historically depresses winning percentage significantly in NBA"
    ],
    "anchor_players": [],
    "drafted_at": "2026-03-11T14:00:00"
  }
];
